#ifndef TINYFS_ERRNO_H
#define TINYFS_ERRNO_H

#define TFS_SUCCESS 1
#define TFS_ERROR_NO_DISK_MOUNTED -1
#define TFS_ERROR_INVALID_FS -2
#define TFS_ERROR_DISK_READ -3
#define TFS_ERROR_DISK_OPEN -4
#define TFS_ERROR_DISK_MOUNTED -5
#define TFS_ERROR_DISK_WRITE -6
#define TFS_ERROR_INVALID_FD -7
#define TFS_ERROR_MAX_FILES_REACHED -8
#define TFS_ERROR_DISK_FULL -9
#define TFS_ERROR_END_OF_FILE -10
#define TFS_ERROR_INVALID_OFFSET -11
#define TFS_ERROR_INVALID_DISK_SIZE -12
#define TFS_ERROR_INVALID_PARAMETER -13
#define TFS_ERROR_EMPTY_FILE -14
#define TFS_ERROR_BAD_ALLOC -15
#define TFS_ERROR_BAD_MAGIC -16
#define TFS_ERROR_FILE_OPEN -17
#define TFS_ERROR_TRUNC -18
#define TFS_ERROR_VALIDATE -19
#define TFS_ERROR_UNK -20

#endif